deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,22 +37,23 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/cleonora-miahkykh:latest
 
-#      - name: SSH Restart PostgreSQL container
-#        uses: appleboy/ssh-action@v1.2.1
-#        with:
-#          host: ${{ secrets.SSH_HOST }}
-#          username: ${{ secrets.SSH_USERNAME }}
-#          password: ${{ secrets.SSH_PASSWORD }}
-#          port: 22
-#          script: |
-#            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
-#            echo "Restarting PostgreSQL container"
-#
-#            docker stop cleonora-db || echo "PostgreSQL container not running"
-#            docker rm cleonora-db || echo "PostgreSQL container not found"
-#            docker pull postgres:latest
-#            docker run -d --name cleonora-db --net cleonora-network -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=postgres -p 5440:5432 postgres:latest
-#            echo "PostgreSQL container has been updated"
+      - name: SSH Restart PostgreSQL container
+        uses: appleboy/ssh-action@v1.2.1
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          password: ${{ secrets.SSH_PASSWORD }}
+          port: 22
+          script: |
+            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
+            echo "Restarting PostgreSQL container"
+
+            docker stop cleonora-db || echo "PostgreSQL container not running"
+            docker rm cleonora-db || echo "PostgreSQL container not found"
+            docker pull postgres:latest
+            docker run -d --name cleonora-db --net cleonora-network -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=postgres -p 5440:5432 postgres:latest
+            echo "PostgreSQL container has been updated"
+            docker exec cleonora-db psql -U postgres -d postgres -c "CREATE DATABASE cleonora_database;"
 
       - name: SSH Restart CleonoraAdmin container
         uses: appleboy/ssh-action@v1.2.1
