deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,7 +37,7 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/cleonora-miahkykh:latest
 
-      - name: SSH Deploy with Docker Compose
+      - name: SSH Restart PostgreSQL container
         uses: appleboy/ssh-action@v1.2.1
         with:
           host: ${{ secrets.SSH_HOST }}
@@ -45,9 +45,29 @@ jobs:
           password: ${{ secrets.SSH_PASSWORD }}
           port: 22
           script: |
-            echo "Checking SSH credentials and permissions"
-            ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "whoami"
-            ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "touch /projects/CleonoraApp-R.Miahkykh/test.txt"
             docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
-            echo "Copying docker-compose.yml to remote server"
-            scp -o StrictHostKeyChecking=no -P 22 ./docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/projects/CleonoraApp-R.Miahkykh/docker-compose.yml
+            echo "Restarting PostgreSQL container"
+
+            docker stop cleonora-db || echo "PostgreSQL container not running"
+            docker rm cleonora-db || echo "PostgreSQL container not found"
+            docker pull postgres:latest
+            docker run -d --name cleonora-db --net cleonora-network -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=postgres -p 5440:5432 postgres:latest
+            echo "PostgreSQL container has been updated"
+
+      - name: SSH Restart CleonoraAdmin container
+        uses: appleboy/ssh-action@v1.2.1
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          password: ${{ secrets.SSH_PASSWORD }}
+          port: 22
+          script: |
+            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
+            echo "Restarting CleonoraAdmin container"
+
+            docker stop cleonora-admin || echo "CleonoraAdmin container not running"
+            docker rm cleonora-admin || echo "CleonoraAdmin container not found"
+            docker pull glyuchnoglaz21/cleonora-miahkykh:latest
+            
+            docker run -d --name cleonora-admin --network cleonora-network -e SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} -e SPRING_DATASOURCE_URL=jdbc:postgresql://cleonora-db:5432/postgres -e SPRING_DATASOURCE_USERNAME=postgres -e SPRING_DATASOURCE_PASSWORD=0000 -p 7940:8080 ${{ secrets.DOCKER_USERNAME }}/cleonora-miahkykh:latest
+            echo "CleonoraAdmin container has been updated"
