deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,22 +37,22 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/cleonora-miahkykh:latest
 
-      - name: SSH Restart PostgreSQL container
-        uses: appleboy/ssh-action@v1.2.1
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          port: 22
-          script: |
-            docker network ls | findstr "cleonora-network" > nul || docker network create cleonora-network
-            echo "Restarting PostgreSQL container"
-
-            docker stop cleonora-db || echo "PostgreSQL container not running"
-            docker rm cleonora-db || echo "PostgreSQL container not found"
-            docker pull postgres:latest
-            docker run -d --name cleonora-db --net cleonora-network -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=postgres -p 5432:5432 postgres:latest
-            echo "PostgreSQL container has been updated"
+#      - name: SSH Restart PostgreSQL container
+#        uses: appleboy/ssh-action@v1.2.1
+#        with:
+#          host: ${{ secrets.SSH_HOST }}
+#          username: ${{ secrets.SSH_USERNAME }}
+#          password: ${{ secrets.SSH_PASSWORD }}
+#          port: 22
+#          script: |
+#            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
+#            echo "Restarting PostgreSQL container"
+#
+#            docker stop cleonora-db || echo "PostgreSQL container not running"
+#            docker rm cleonora-db || echo "PostgreSQL container not found"
+#            docker pull postgres:latest
+#            docker run -d --name cleonora-db --net cleonora-network -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=postgres -p 5440:5432 postgres:latest
+#            echo "PostgreSQL container has been updated"
 
       - name: SSH Restart CleonoraAdmin container
         uses: appleboy/ssh-action@v1.2.1
@@ -62,12 +62,12 @@ jobs:
           password: ${{ secrets.SSH_PASSWORD }}
           port: 22
           script: |
-            docker network ls | findstr "cleonora-network" > nul || docker network create cleonora-network
+            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
             echo "Restarting CleonoraAdmin container"
 
             docker stop cleonora-admin || echo "CleonoraAdmin container not running"
             docker rm cleonora-admin || echo "CleonoraAdmin container not found"
             docker pull glyuchnoglaz21/cleonora-miahkykh:latest
             
-            docker run -d --name cleonora-app --network cleonora-network -e SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} -e SPRING_DATASOURCE_URL=jdbc:postgresql://cleonora-db:5432/postgres -e SPRING_DATASOURCE_USERNAME=postgres -e SPRING_DATASOURCE_PASSWORD=0000 -p 7940:8081 glyuchnoglaz21/cleonora-miahkykh
+            docker run -d --name cleonora-admin --network cleonora-network -e SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} -e SPRING_DATASOURCE_URL=jdbc:postgresql://cleonora-db:5432/postgres -e SPRING_DATASOURCE_USERNAME=postgres -e SPRING_DATASOURCE_PASSWORD=0000 -p 7940:8080 ${{ secrets.DOCKER_USERNAME }}/cleonora-miahkykh:latest
             echo "CleonoraAdmin container has been updated"
